/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biarpinter;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author leorence
 */
public class radioCombo extends javax.swing.JFrame {
    final static String Driver = "com.mysql.jdbc.Driver";
    final static String Url = "jdbc:mysql://localhost/univ";
    final static String User = "root";
    final static String Pass = "";
    static Connection conn;
    static PreparedStatement st;
    static ResultSet rs;
    /**
     * Creates new form radioButton
     */
    public radioCombo() {
        initComponents();
        user.setSelected(true);
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getWidth() / 2;
        int y = layar.height / 2 - this.getHeight() / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelamin = new javax.swing.ButtonGroup();
        adminmode = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nima = new javax.swing.JTextField();
        namaa = new javax.swing.JTextField();
        pria = new javax.swing.JRadioButton();
        wanita = new javax.swing.JRadioButton();
        bencong = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jurusana = new javax.swing.JComboBox<>();
        mhs = new javax.swing.JButton();
        am = new javax.swing.JRadioButton();
        user = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Universitas Maju Mundur");

        jLabel2.setText("Nama   :");

        jLabel3.setText("Nim      :");

        jLabel4.setText("Jurusan :");

        jeniskelamin.add(pria);
        pria.setText("Pria");

        jeniskelamin.add(wanita);
        wanita.setText("Wanita");

        jeniskelamin.add(bencong);
        bencong.setText("Bencong");

        jButton1.setText("Lihat!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jurusana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jurusan", "Information System", "Mobile Internet & Technology", "Design Communication Visual", "Accountant", "Management" }));
        jurusana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanaActionPerformed(evt);
            }
        });

        mhs.setText("List Mahasiswa");
        mhs.setEnabled(false);
        mhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhsActionPerformed(evt);
            }
        });

        adminmode.add(am);
        am.setText("Admin Mode");
        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });

        adminmode.add(user);
        user.setText("User");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mhs))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(pria)
                                        .addGap(62, 62, 62)
                                        .addComponent(wanita)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bencong))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(namaa, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(27, 27, 27)
                                        .addComponent(nima, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(26, 26, 26)
                                        .addComponent(jurusana, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(am)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(am)
                    .addComponent(user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nima, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jurusana, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pria)
                    .addComponent(wanita)
                    .addComponent(bencong))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(mhs))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jurusana.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String isi = "";
        String y = null;
        String na = namaa.getText();
        String ni = nima.getText();
        if (na.equals("")) {
            JOptionPane.showMessageDialog(null, "Tolong masukkan nama anda");
        } else {
            na = namaa.getText();
        }
        if (ni.equals("")) {
            JOptionPane.showMessageDialog(null, "Tolong masukkan nim anda");
        } 
        else {
            ni = nima.getText();
        }
        int pilih = jurusana.getSelectedIndex();
        String x[] = new String[pilih];
        for (int i = 0; i < pilih; i++) {
           x[i] = String.valueOf(jurusana.getSelectedItem());
           y = x[i];
        }
        String jk = "";
        if (pria.isSelected()) {
            jk = pria.getText();
        } else if (wanita.isSelected()) {
            jk = wanita.getText();
        } else if (bencong.isSelected()) {
            jk = bencong.getText();
        } else {
            JOptionPane.showMessageDialog(null, "Tolong masukkan jenis kelamin anda!");
        }
        
        // jika auto increment isi "null"
//        String jur = jurusan;
//        String jeka = jk;
        try {
            conn = DriverManager.getConnection(Url, User, Pass);
            String sql = "INSERT INTO data VALUES (?,?,?,?);";
            st = conn.prepareStatement(sql);
            st.setString(1, na);
            st.setString(2, ni);
            st.setString(3, y);
            st.setString(4, jk);
            if (na.equals("") || ni.equals("") || jk.equals("") || y.equals("Jurusan")) {
                JOptionPane.showMessageDialog(null, "Mohon isi data terlebih dahulu");
            } else {
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data telah di tambahkan");
                reset();
            }
        } catch (Exception e) {
            System.err.println("Error : "+e);
            JOptionPane.showMessageDialog(null, "Gagal memasukkan data,\nAda data yang belum diisi.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed
       try{
        if (am.isSelected()) {
            String x = JOptionPane.showInputDialog("Masukkan password admin");
             if (x.equals("9455")) {
                mhs.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Password yang di masukkan salah,\nHubungi admin kami!");
                user.setSelected(true);
            }
        }
       } catch(Exception x){
           user.setSelected(true);
       }
    }//GEN-LAST:event_amActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        if (user.isSelected()) {
            mhs.setEnabled(false);
        }
    }//GEN-LAST:event_userActionPerformed

    private void mhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhsActionPerformed
        listMhs c = new listMhs();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mhsActionPerformed

    private void jurusanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(radioCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(radioCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(radioCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(radioCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new radioCombo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup adminmode;
    private javax.swing.JRadioButton am;
    private javax.swing.JRadioButton bencong;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.JComboBox<String> jurusana;
    private javax.swing.JButton mhs;
    private javax.swing.JTextField namaa;
    private javax.swing.JTextField nima;
    private javax.swing.JRadioButton pria;
    private javax.swing.JRadioButton user;
    private javax.swing.JRadioButton wanita;
    // End of variables declaration//GEN-END:variables
private void reset(){
    namaa.setText("");
    nima.setText("");
    jeniskelamin.clearSelection();
    jurusana.setSelectedIndex(0);
}
}