/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import data_class.identity;
import handler.data_akses_id;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author leorence
 */
public class identitas extends javax.swing.JFrame {

    /**
     * Creates new form idpengirim
     */
    public identitas() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        int x = layar.width / 2 - this.getWidth() / 2;
        int y = layar.height / 2 - this.getHeight() / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idp = new javax.swing.JTextField();
        np = new javax.swing.JTextField();
        prov = new javax.swing.JComboBox<>();
        kk = new javax.swing.JComboBox<>();
        kec = new javax.swing.JComboBox<>();
        kel = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kodep = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        street = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        nope = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Identitas Penerima");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("<");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("ID_Penerima                 :");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Nama                           :");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Provinsi                        :");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Kota / Kabupaten          :");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setText("Kecamatan                   :");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Kelurahan                    :");

        idp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        idp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpActionPerformed(evt);
            }
        });

        np.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });

        prov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Jawa Barat", "Jawa Tengah", "Jawa Timur" }));
        prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provActionPerformed(evt);
            }
        });

        kk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        kk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kkActionPerformed(evt);
            }
        });

        kec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kecActionPerformed(evt);
            }
        });

        kel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Kode pos                     :");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Alamat Jelas                :");

        kodep.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        kodep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodepActionPerformed(evt);
            }
        });

        street.setColumns(20);
        street.setRows(5);
        jScrollPane2.setViewportView(street);

        jButton1.setText("Input data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setText("Nomor Telepon           :");

        nope.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nopeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(prov, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kec, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kodep, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(nope, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(prov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(kk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(kec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(kodep, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nope, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        IPP x = new IPP();
        x.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void idpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpActionPerformed

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npActionPerformed

    private void kodepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodepActionPerformed

    private void nopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nopeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nopeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        identity x = new identity();
        int id_p = Integer.parseInt(idp.getText());
        String nama = np.getText();
        String kp = kodep.getText();
        String jl = street.getText();
        String nofe = nope.getText();
        x.setId_penerima(id_p);
        x.setNama(nama);
        x.setProvinsi(prov.getSelectedItem().toString());
        x.setKotkab(kk.getSelectedItem().toString());
        x.setKec(kec.getSelectedItem().toString());
        x.setKel(kel.getSelectedItem().toString());
        x.setKp(kp);
        x.setStreet(jl);
        x.setNotelp(nofe);
        boolean status = data_akses_id.insertData(x);
        if (!status) {
            JOptionPane.showMessageDialog(null, "Data inserted successfully");
            IPP y = new IPP();
            y.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Data not inserted");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provActionPerformed
        try{
        switch (prov.getSelectedIndex()) {
            case 1:
                kk.addItem("Cimahi");
                kk.addItem("Bandung");
                kk.addItem("Sukabumi");
                prov.setEnabled(false);
                break;
            case 2:
                kk.addItem("Tegal");
                kk.addItem("Semarang");
                kk.addItem("Wonosobo");
                prov.setEnabled(false);
                break;
            case 3:
                kk.addItem("Malang");
                kk.addItem("Kediri");
                kk.addItem("Sumenep");
                prov.setEnabled(false);
                break;
            default:
                
                break;
        }
        } catch (Exception e) {
            System.err.println("Error : "+e);
        }
    }//GEN-LAST:event_provActionPerformed

    private void kkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kkActionPerformed
        if (kk.getSelectedItem().equals("Cimahi")) {
            kec.removeAllItems();
            kec.addItem("Cimahi Utara");
            kec.addItem("Cimahi Tengah");
            kec.addItem("Cimahi Selatan");
            kk.setEnabled(false);
        } else if (kk.getSelectedItem().equals("Bandung")) {
            kec.removeAllItems();
            kec.addItem("Coblong");
            kec.addItem("Gedebage");
            kec.addItem("Sukasari");
            kk.setEnabled(false);
        } else if (kk.getSelectedItem().equals("Sukabumi")) {
            kec.removeAllItems();
            kec.addItem("Cidahu");
            kec.addItem("Cidadap");
            kec.addItem("Cikakak");
            kk.setEnabled(false);
        } else if (kk.getSelectedItem().equals("Tegal")) {
            kec.removeAllItems();
            kec.addItem("Tegal Barat");
            kec.addItem("Tegal Selatan");
            kec.addItem("Tegal Timur");
            kk.setEnabled(false);
        } else if (kk.getSelectedItem().equals("Semarang")) {
            kec.removeAllItems();
            kec.addItem("Gunungpati");
            kec.addItem("Mijen");
            kec.addItem("Ngaliyan");
            kk.setEnabled(false);
        } else if (kk.getSelectedItem().equals("Wonosobo")) {
            kec.removeAllItems();
            kec.addItem("Selomerto");
            kec.addItem("Mojotengah");
            kec.addItem("Kertek");
            kk.setEnabled(false);
        } else if (kk.getSelectedItem().equals("Malang")) {
            kec.removeAllItems();
            kec.addItem("Lowokwaru");
            kec.addItem("Klojen");
            kec.addItem("Sukun");
            kk.setEnabled(false);
        } else if (kk.getSelectedItem().equals("Kediri")) {
            kec.removeAllItems();
            kec.addItem("Mojo");
            kec.addItem("Semen");
            kec.addItem("Grogol");
            kk.setEnabled(false);
        } else if (kk.getSelectedItem().equals("Sumenep")) {
            kec.removeAllItems();
            kec.addItem("Gapura");
            kec.addItem("Bluto");
            kec.addItem("Arjasa");
            kk.setEnabled(false);
        }
    }//GEN-LAST:event_kkActionPerformed

    private void kelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelActionPerformed
        
    }//GEN-LAST:event_kelActionPerformed

    private void kecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kecActionPerformed
        if (kec.getSelectedItem().equals("Cimahi Utara")) {
            kel.removeAllItems();
            kel.addItem("Cipageran");
            kel.addItem("Cibabat");
            kel.addItem("Citereup");
        } else if (kec.getSelectedItem().equals("Cimahi Tengah")) {
            kel.removeAllItems();
            kel.addItem("Baros");
            kel.addItem("Padasuka");
            kel.addItem("Cigugur");
        } else if (kec.getSelectedItem().equals("Cimahi Selatan")) {
            kel.removeAllItems();
            kel.addItem("Leuwigajah");
            kel.addItem("Melong");
            kel.addItem("Cibeureum");
        } else if (kec.getSelectedItem().equals("Coblong")) {
            kel.removeAllItems();
            kel.addItem("Dago");
            kel.addItem("Sekeloa");
            kel.addItem("Lebakgede");
        } else if (kec.getSelectedItem().equals("Gedebage")) {
            kel.removeAllItems();
            kel.addItem("Cimincrang");
            kel.addItem("Rancabolang");
            kel.addItem("Rancanumpang");
        } else if (kec.getSelectedItem().equals("Sukasari")) {
            kel.removeAllItems();
            kel.addItem("Gegerkalong");
            kel.addItem("Sarijadi");
            kel.addItem("Isola");
        } else if (kec.getSelectedItem().equals("Cidahu")) {
            kel.removeAllItems();
            kel.addItem("Girijaya");
            kel.addItem("Jayabakti");
            kel.addItem("Tangkil");
        } else if (kec.getSelectedItem().equals("Cidadap")) {
            kel.removeAllItems();
            kel.addItem("Banjarsari");
            kel.addItem("Hegarmulya");
            kel.addItem("Padasenang");
        } else if (kec.getSelectedItem().equals("Cikakak")) {
            kel.removeAllItems();
            kel.addItem("Cileungsing");
            kel.addItem("Cirendang");
            kel.addItem("Sukamaju");
        } else if (kec.getSelectedItem().equals("Tegal Barat")) {
            kel.removeAllItems();
            kel.addItem("Kraton");
            kel.addItem("Pekauman");
            kel.addItem("Tegalsari");
        } else if (kec.getSelectedItem().equals("Tegal Timur")) {
            kel.removeAllItems();
            kel.addItem("Kejambon");
            kel.addItem("Panggung");
            kel.addItem("Slerok");
        } else if (kec.getSelectedItem().equals("Tegal Selatan")) {
            kel.removeAllItems();
            kel.addItem("Bandung");
            kel.addItem("Tunon");
            kel.addItem("Keturen");
        } else if (kec.getSelectedItem().equals("Gunungpati")) {
            kel.removeAllItems();
            kel.addItem("Sukorejo");
            kel.addItem("Ngijo");
            kel.addItem("Cepoko");
        } else if (kec.getSelectedItem().equals("Mijen")) {
            kel.removeAllItems();
            kel.addItem("Jatisari");
            kel.addItem("Pesantren");
            kel.addItem("Cangkiran");
        } else if (kec.getSelectedItem().equals("Ngaliyan")) {
            kel.removeAllItems();
            kel.addItem("Wonosari");
            kel.addItem("Wates");
            kel.addItem("Podorejo");
        } else if (kec.getSelectedItem().equals("Selomerto")) {
            kel.removeAllItems();
            kel.addItem("Bomerto");
            kel.addItem("Bumireso");
            kel.addItem("Jaraksari");
        } else if (kec.getSelectedItem().equals("Mojotengah")) {
            kel.removeAllItems();
            kel.addItem("Kejiwan");
            kel.addItem("Kramatan");
            kel.addItem("Mlipak");
        } else if (kec.getSelectedItem().equals("Kertek")) {
            kel.removeAllItems();
            kel.addItem("Sambek");
            kel.addItem("Tlogojati");
            kel.addItem("Sariyoso");
        } else if (kec.getSelectedItem().equals("Lowokwaru")) {
            kel.removeAllItems();
            kel.addItem("Sumbersari");
            kel.addItem("Dinoyo");
            kel.addItem("Tlogomas");
        } else if (kec.getSelectedItem().equals("Klojen")) {
            kel.removeAllItems();
            kel.addItem("Samaan");
            kel.addItem("Bareng");
            kel.addItem("Kasin");
        } else if (kec.getSelectedItem().equals("Sukun")) {
            kel.removeAllItems();
            kel.addItem("Kebonsari");
            kel.addItem("Pisangcandi");
            kel.addItem("Gadang");
        } else if (kec.getSelectedItem().equals("Mojo")) {
            kel.removeAllItems();
            kel.addItem("Kraton");
            kel.addItem("Surat");
            kel.addItem("Jugo");
        } else if (kec.getSelectedItem().equals("Semen")) {
            kel.removeAllItems();
            kel.addItem("Bulu");
            kel.addItem("Sidomulyo");
            kel.addItem("Bobang");
        } else if (kec.getSelectedItem().equals("Grogol")) {
            kel.removeAllItems();
            kel.addItem("Wonoasri");
            kel.addItem("Bakalan");
            kel.addItem("Kalipang");
        } else if (kec.getSelectedItem().equals("Gapura")) {
            kel.removeAllItems();
            kel.addItem("Poja");
            kel.addItem("Longos");
            kel.addItem("Mandala");
        } else if (kec.getSelectedItem().equals("Bluto")) {
            kel.removeAllItems();
            kel.addItem("Lobuk");
            kel.addItem("Palongan");
            kel.addItem("Errabu");
        } else if (kec.getSelectedItem().equals("Arjasa")) {
            kel.removeAllItems();
            kel.addItem("Angkatan");
            kel.addItem("Duko");
            kel.addItem("Gelaman");
        }
    }//GEN-LAST:event_kecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(identitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(identitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(identitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(identitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new identitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> kec;
    private javax.swing.JComboBox<String> kel;
    private javax.swing.JComboBox<String> kk;
    private javax.swing.JTextField kodep;
    private javax.swing.JTextField nope;
    private javax.swing.JTextField np;
    private javax.swing.JComboBox<String> prov;
    private javax.swing.JTextArea street;
    // End of variables declaration//GEN-END:variables
}
